### ISSUE TITLE
Error with vis

### ISSUE THREAD

**Issue by moniquewong** [UBC-MDS/DSCI_522_Group_303#68]
I get the following error when I run `make all` after the vis updates:

`Traceback (most recent call last):
  File "src/explore_data.py", line 93, in <module>
    test_images_created()
  File "src/explore_data.py", line 88, in test_images_created
    main('data/train_data.csv', 'output')
  File "src/explore_data.py", line 63, in main
    concat_1_2 = (number_of_properties_by_price | Neighborhoods).configure_title(fontSize=20
  File "/Users/moniquewong/anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 504, in __or__
    return hconcat(self, other)
  File "/Users/moniquewong/anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 1771, in hconcat
    return HConcatChart(hconcat=charts, **kwargs)
  File "/Users/moniquewong/anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 1744, in __init__
    _check_if_valid_subspec(spec, 'HConcatChart')
  File "/Users/moniquewong/anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 1609, in _check_if_valid_subspec
    raise ValueError(err.format(attr, classname))
ValueError: Objects with "config" attribute cannot be used within HConcatChart. Consider defining the config attribute in the HConcatChart object instead.
make: *** [output/neighborhoods.png] Error 1`

**Comment by moniquewong** [comment]
Fixed by removing `.configure` in base charts
